const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadData: () => ipcRenderer.invoke('load-data'),
  saveData: (data) => ipcRenderer.invoke('save-data', data),
  dataFilePath: () => ipcRenderer.invoke('data-file-path'),
  stravaSync: (creds) => ipcRenderer.invoke('strava-sync', creds),
  stravaActivityDetails: (data) => ipcRenderer.invoke('strava-activity-details', data),
  getActivityStreams: (activityId) => ipcRenderer.invoke('get-activity-streams', activityId),
  fetchAudax: () => ipcRenderer.invoke('audax-fetch'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openAudaxUrl: (url) => ipcRenderer.invoke('open-audax-url', url),
  saveZwo: (data) => ipcRenderer.invoke('save-zwo', data),
  saveGpx: (data) => ipcRenderer.invoke('save-gpx', data),
  saveRideGpx: (data) => ipcRenderer.invoke('save-ride-gpx', data),
  showOpenDialog: (opts) => ipcRenderer.invoke('show-open-dialog', opts),
  checkAudaxFiles: (url) => ipcRenderer.invoke('audax-check-files', url),
  fetchAudaxElevation: (url) => ipcRenderer.invoke('audax-fetch-elevation', url),
  downloadAudaxFile: (data) => ipcRenderer.invoke('audax-download-file', data),
  whoopAuth: (creds) => ipcRenderer.invoke('whoop-auth', creds),
  whoopSync: (creds) => ipcRenderer.invoke('whoop-sync', creds),
  garminSync: (creds) => ipcRenderer.invoke('garmin-sync', creds),
  rwgpsSync: (data) => ipcRenderer.invoke('rwgps-sync', data),
  microsoftAuth: (data) => ipcRenderer.invoke('microsoft-auth', data),
  microsoftRefresh: (data) => ipcRenderer.invoke('microsoft-refresh', data),
  microsoftGetEvents: (data) => ipcRenderer.invoke('microsoft-get-events', data),
  microsoftAddEvent: (data) => ipcRenderer.invoke('microsoft-add-event', data),
  microsoftGetUser: (data) => ipcRenderer.invoke('microsoft-get-user', data),
  setAudaxCreds: (data) => ipcRenderer.invoke('set-audax-creds', data),
  onedriveSave: (data) => ipcRenderer.invoke('onedrive-save', data),
  onedriveLoad: (data) => ipcRenderer.invoke('onedrive-load', data),
  onedriveUploadFile: (data) => ipcRenderer.invoke('onedrive-upload-file', data),
  onedriveFileUrl: (data) => ipcRenderer.invoke('onedrive-file-url', data),

  // App updates
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (event, info) => callback(info)),
  onUpdateDownloadProgress: (callback) => ipcRenderer.on('update-download-progress', (event, progress) => callback(progress)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (event, info) => callback(info)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (event, error) => callback(error)),
});
