const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadData: () => ipcRenderer.invoke('load-data'),
  saveData: (data) => ipcRenderer.invoke('save-data', data),
  dataFilePath: () => ipcRenderer.invoke('data-file-path'),
  stravaSync: (creds) => ipcRenderer.invoke('strava-sync', creds),
  getActivityStreams: (activityId) => ipcRenderer.invoke('get-activity-streams', activityId),
  fetchAudax: () => ipcRenderer.invoke('audax-fetch'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openAudaxUrl: (url) => ipcRenderer.invoke('open-audax-url', url),
  saveZwo: (data) => ipcRenderer.invoke('save-zwo', data),
  saveGpx: (data) => ipcRenderer.invoke('save-gpx', data),
  saveRideGpx: (data) => ipcRenderer.invoke('save-ride-gpx', data),
  showOpenDialog: (opts) => ipcRenderer.invoke('show-open-dialog', opts),
  checkAudaxFiles: (url) => ipcRenderer.invoke('audax-check-files', url),
  fetchAudaxElevation: (url) => ipcRenderer.invoke('audax-fetch-elevation', url),
  downloadAudaxFile: (data) => ipcRenderer.invoke('audax-download-file', data),
  whoopAuth: (creds) => ipcRenderer.invoke('whoop-auth', creds),
  whoopSync: (creds) => ipcRenderer.invoke('whoop-sync', creds),
  garminSync: (creds) => ipcRenderer.invoke('garmin-sync', creds),
  microsoftAuth: (data) => ipcRenderer.invoke('microsoft-auth', data),
  microsoftRefresh: (data) => ipcRenderer.invoke('microsoft-refresh', data),
  microsoftGetEvents: (data) => ipcRenderer.invoke('microsoft-get-events', data),
  microsoftAddEvent: (data) => ipcRenderer.invoke('microsoft-add-event', data),
  microsoftGetUser: (data) => ipcRenderer.invoke('microsoft-get-user', data),
  setAudaxCreds: (data) => ipcRenderer.invoke('set-audax-creds', data),
  onedriveSave: (data) => ipcRenderer.invoke('onedrive-save', data),
  onedriveLoad: (data) => ipcRenderer.invoke('onedrive-load', data),
  onedriveUploadFile: (data) => ipcRenderer.invoke('onedrive-upload-file', data),
  onedriveFileUrl: (data) => ipcRenderer.invoke('onedrive-file-url', data),
});
